/**
 * AudioClips — Centralized narration system for GCU.
 *
 * Plays pre-recorded WAV clips (generated by piper) via AudioManager.
 * Falls back transparently to speechSynthesis when a WAV is not yet available.
 *
 * Usage:
 *   // Once, during game init:
 *   await AudioClips.getInstance().loadGame('puzzle-forest', 'games/puzzle-forest/assets/audio');
 *
 *   // To speak a clip:
 *   AudioClips.getInstance().speak('puzzle-forest', 'build_fox');
 *
 *   // To speak a random clip from a set (praise, retry, etc.):
 *   AudioClips.getInstance().speakRandom('puzzle-forest', 'praise_');
 *
 *   // In scene.exit():
 *   AudioClips.getInstance().cancel();
 *
 * See docs/AudioClips.md for full design documentation.
 */

import { AudioManager } from './AudioManager.js';

let instance = null;

export class AudioClips {
  static getInstance() {
    if (!instance) instance = new AudioClips();
    return instance;
  }

  constructor() {
    /** @type {Map<string, { clips: Map<string, string>, clipsBasePath: string }>} */
    this._games = new Map();

    /** @type {Set<string>} Keys that have been successfully loaded into AudioManager */
    this._loaded = new Set();

    /** @type {Set<string>} Keys whose WAV fetch failed — skip on future calls */
    this._failed = new Set();

    /** @type {SpeechSynthesisUtterance|null} */
    this._utterance = null;
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Load a game's audio-config.json and all its manifest files.
   * Safe to call multiple times — duplicate calls for the same gameId are ignored.
   *
   * @param {string} gameId       e.g. 'puzzle-forest'
   * @param {string} audioBasePath  URL path to the game's assets/audio/ directory
   *                              e.g. 'games/puzzle-forest/assets/audio'
   * @returns {Promise<void>}
   */
  async loadGame(gameId, audioBasePath) {
    if (this._games.has(gameId)) return;

    try {
      const configUrl = `${audioBasePath}/audio-config.json`;
      const configRes = await fetch(configUrl);
      if (!configRes.ok) {
        console.warn(`[AudioClips] Config not found: ${configUrl}`);
        return;
      }
      const config = await configRes.json();
      const clips = new Map();
      const clipsDir = config.clipsDir ?? 'clips';

      for (const manifestFile of (config.manifests ?? [])) {
        try {
          const res = await fetch(`${audioBasePath}/${manifestFile}`);
          if (!res.ok) continue;
          const text = await res.text();
          for (const rawLine of text.split('\n')) {
            const line = rawLine.trim();
            if (!line || line.startsWith('#')) continue;
            const pipeIdx = line.indexOf('|');
            if (pipeIdx < 1) continue;
            const key = line.slice(0, pipeIdx).trim();
            const spoken = line.slice(pipeIdx + 1).trim();
            if (key && spoken) clips.set(key, spoken);
          }
        } catch (e) {
          console.warn(`[AudioClips] Failed to load manifest ${manifestFile}:`, e);
        }
      }

      this._games.set(gameId, {
        clips,
        clipsBasePath: `${audioBasePath}/${clipsDir}`,
      });
      console.log(`[AudioClips] ${gameId}: ${clips.size} clips registered`);
    } catch (e) {
      console.warn(`[AudioClips] loadGame failed for ${gameId}:`, e);
    }
  }

  /**
   * Speak a clip by key. Tries WAV first; falls back to speechSynthesis.
   * Fire-and-forget — returns immediately without waiting for speech to finish.
   *
   * @param {string} gameId
   * @param {string} key
   * @param {{ rate?: number, pitch?: number, volume?: number }} [opts]
   *   Options apply only to the speechSynthesis fallback path.
   */
  speak(gameId, key, opts = {}) {
    const game = this._games.get(gameId);
    if (!game) {
      console.warn(`[AudioClips] Game not loaded: ${gameId}`);
      return;
    }
    const text = game.clips.get(key);
    if (!text) {
      console.warn(`[AudioClips] Unknown clip key: ${gameId}:${key}`);
      return;
    }

    this.cancel();
    this._playClip(gameId, key, text, game.clipsBasePath, opts);
  }

  /**
   * Speak a clip by key, automatically using random variants if they exist.
   * If `baseKey + '_01'` is registered, delegates to speakRandom(baseKey + '_').
   * Otherwise falls back to speak(baseKey). This lets callers always use the
   * base key (e.g. 'sort_green') without knowing whether variants exist.
   *
   * @param {string} gameId
   * @param {string} baseKey  e.g. 'sort_green' or 'build_fox'
   * @param {{ rate?: number, pitch?: number, volume?: number }} [opts]
   */
  speakPrompt(gameId, baseKey, opts = {}) {
    const game = this._games.get(gameId);
    if (!game) {
      console.warn(`[AudioClips] Game not loaded: ${gameId}`);
      return;
    }
    // Check if numbered variants exist (baseKey_01, baseKey_02, …)
    if (game.clips.has(`${baseKey}_01`)) {
      this.speakRandom(gameId, `${baseKey}_`, opts);
    } else {
      this.speak(gameId, baseKey, opts);
    }
  }

  /**
   * Speak a random clip whose key starts with prefix.
   * Example: speakRandom('puzzle-forest', 'praise_') picks from praise_01, praise_02, …
   *
   * @param {string} gameId
   * @param {string} prefix
   * @param {{ rate?: number, pitch?: number, volume?: number }} [opts]
   */
  speakRandom(gameId, prefix, opts = {}) {
    const game = this._games.get(gameId);
    if (!game) return;
    const matching = [...game.clips.keys()].filter((k) => k.startsWith(prefix));
    if (!matching.length) return;
    const key = matching[Math.floor(Math.random() * matching.length)];
    this.speak(gameId, key, opts);
  }

  /**
   * Stop any in-progress narration (WAV or TTS).
   * Call from every scene.exit().
   */
  cancel() {
    try {
      if (window.speechSynthesis) window.speechSynthesis.cancel();
    } catch (_) { /* ignore */ }
    this._utterance = null;
  }

  /**
   * Returns true if the WAV for this key has been successfully loaded.
   * Useful for debugging — AudioClips.isAvailable('puzzle-forest', 'build_fox').
   *
   * @param {string} gameId
   * @param {string} key
   * @returns {boolean}
   */
  isAvailable(gameId, key) {
    return this._loaded.has(`clips:${gameId}:${key}`);
  }

  /**
   * Returns all registered clips as 'key|text' lines, one per line.
   * Useful in the browser console to audit what's registered.
   *
   * @param {string} gameId
   * @returns {string}
   */
  exportManifest(gameId) {
    const game = this._games.get(gameId);
    if (!game) return '';
    return [...game.clips.entries()].map(([k, v]) => `${k}|${v}`).join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private
  // ---------------------------------------------------------------------------

  /**
   * Attempt to play a WAV clip. Falls back to TTS if the WAV isn't available.
   * Async internally, but callers don't need to await — it's fire-and-forget.
   *
   * @param {string} gameId
   * @param {string} key
   * @param {string} text
   * @param {string} clipsBasePath
   * @param {object} opts
   */
  async _playClip(gameId, key, text, clipsBasePath, opts) {
    const audioKey = `clips:${gameId}:${key}`;
    const audio = AudioManager.getInstance();

    // AudioContext must be unlocked (requires a prior user gesture).
    // If it's not ready yet, fall back to TTS without caching the failure —
    // the WAV might work fine once the user has clicked something.
    if (!audio.audioContext) {
      this._fallback(text, opts);
      return;
    }

    // Already loaded and confirmed working — play immediately.
    if (this._loaded.has(audioKey)) {
      audio.play(audioKey, { volume: opts.volume ?? 1 });
      return;
    }

    // Previously confirmed missing — skip straight to TTS.
    if (this._failed.has(audioKey)) {
      this._fallback(text, opts);
      return;
    }

    // First time: attempt to load the WAV.
    const wavUrl = `${clipsBasePath}/${key}.wav`;
    await audio.load(audioKey, wavUrl, 'speech');

    if (audio.sounds.has(audioKey)) {
      // Loaded successfully.
      this._loaded.add(audioKey);
      audio.play(audioKey, { volume: opts.volume ?? 1 });
    } else {
      // Load silently failed (404 or decode error).
      this._failed.add(audioKey);
      this._fallback(text, opts);
    }
  }

  /**
   * Use the browser's speechSynthesis as a fallback narrator.
   *
   * @param {string} text
   * @param {{ rate?: number, pitch?: number, volume?: number }} opts
   */
  _fallback(text, opts = {}) {
    if (typeof window === 'undefined' || !window.speechSynthesis) return;
    try {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate   = opts.rate   ?? 0.9;
      utterance.pitch  = opts.pitch  ?? 1.2;
      utterance.volume = opts.volume ?? 0.8;
      this._utterance  = utterance;
      window.speechSynthesis.speak(utterance);
    } catch (e) {
      console.warn('[AudioClips] TTS fallback failed:', e);
    }
  }
}
